keys:
  - &aurelius 367C18D390C3A808327EAC26FB0436288083EE8B
  - &bemeurer C057AFED6D1499196E046BCB6976C95303C20664
  - &camus 8A6D4D8E5A23070A6A0B8BB3E355C71669A91D46
  - &deleuze FB9ABF8F186420B645D3296D729C8DD8B510C842
  - &foucault 5C8B2ACA031733D4C59A8AF19DE06FED73F48056
  - &fourier A4EABC2BEEE48CFF55287E855FABEC432FE0176B
  - &hegel A2260154AA9528C06164F0FE0F175745C1DB0169
  - &kant 29D3418505A13A593E5E7ABD9F743C14BF7326CC

creation_rules:
  - path_regex: hardware/nixos-aarch64-builder/nixos-aarch64-builder-key.yaml
    key_groups:
      - pgp:
        - *bemeurer
        - *aurelius
        - *camus
        - *deleuze
        - *foucault
        - *hegel
  - path_regex: users/bemeurer/bemeurer-password.yaml
    key_groups:
      - pgp:
        - *bemeurer
        - *aurelius
        - *camus
        - *deleuze
        - *foucault
        - *fourier
        - *hegel
        - *kant
  - path_regex: hosts/aurelius/.*
    key_groups:
      - pgp:
        - *bemeurer
        - *aurelius
  - path_regex: hosts/camus/.*
    key_groups:
      - pgp:
        - *bemeurer
        - *camus
  - path_regex: hosts/deleuze/.*
    key_groups:
      - pgp:
        - *bemeurer
        - *deleuze
  - path_regex: hosts/foucault/.*
    key_groups:
      - pgp:
        - *bemeurer
        - *foucault
  - path_regex: hosts/fourier/.*
    key_groups:
      - pgp:
        - *bemeurer
        - *fourier
  - path_regex: hosts/hegel/.*
    key_groups:
      - pgp:
        - *bemeurer
        - *hegel
  - path_regex: hosts/kant/.*
    key_groups:
      - pgp:
        - *bemeurer
        - *kant
