keys:
  - &bemeurer C057AFED6D1499196E046BCB6976C95303C20664
  - &feuerbach AD5F47941C5378175E46D11A2BB43FA44085673C
  - &foucault 5C8B2ACA031733D4C59A8AF19DE06FED73F48056
  - &fourier A4EABC2BEEE48CFF55287E855FABEC432FE0176B
  - &goethe 3B157FCDEF12BDE6994DA95CA4C02ABF06E9D7E2
  - &riemann 41D56E398857FB3FDF920A2ED3D48D2FCB75EDC3
  - &sartre ACD46795FB2EC5499F10DD01624900F51815907C

creation_rules:
  - path_regex: dev/stcg-x86_64-builder/stcg-x86_64-builder-key.yaml
    key_groups:
      - pgp:
        - *bemeurer
        - *foucault
  - path_regex: hardware/nixos-aarch64-builder/nixos-aarch64-builder-key.yaml
    key_groups:
      - pgp:
        - *bemeurer
        - *feuerbach
        - *foucault
        - *goethe
        - *riemann
  - path_regex: dev/stcg-gcs/stcg-aws-credentials.yaml
    key_groups:
      - pgp:
        - *bemeurer
        - *feuerbach
        - *foucault
        - *fourier
  - path_regex: hosts/sartre/ddclient-sartre.yaml
    key_groups:
      - pgp:
        - *bemeurer
        - *sartre
