keys:
  - &aurelius 367C18D390C3A808327EAC26FB0436288083EE8B
  - &bemeurer C057AFED6D1499196E046BCB6976C95303C20664
  - &cantor 2FB208CEDD87F9392AD0B6D89AAC3DC443B2C338
  - &deleuze 4D25B773C775D9DC267072CAEE861DC14977196F
  - &feuerbach AD5F47941C5378175E46D11A2BB43FA44085673C
  - &foucault 5C8B2ACA031733D4C59A8AF19DE06FED73F48056
  - &fourier A4EABC2BEEE48CFF55287E855FABEC432FE0176B
  - &goethe 3B157FCDEF12BDE6994DA95CA4C02ABF06E9D7E2
  - &hegel A2260154AA9528C06164F0FE0F175745C1DB0169
  - &riemann 41D56E398857FB3FDF920A2ED3D48D2FCB75EDC3
  - &sartre ACD46795FB2EC5499F10DD01624900F51815907C

creation_rules:
  - path_regex: dev/stcg-x86_64-builder/stcg-x86_64-builder-key.yaml
    key_groups:
      - pgp:
        - *bemeurer
        - *foucault
        - *hegel
  - path_regex: hardware/nixos-aarch64-builder/nixos-aarch64-builder-key.yaml
    key_groups:
      - pgp:
        - *aurelius
        - *bemeurer
        - *cantor
        - *deleuze
        - *feuerbach
        - *foucault
        - *goethe
        - *hegel
        - *riemann
  - path_regex: dev/stcg-gcs/stcg-aws-credentials.yaml
    key_groups:
      - pgp:
        - *bemeurer
        - *cantor
        - *feuerbach
        - *foucault
        - *fourier
        - *hegel
  - path_regex: hosts/sartre/ddclient.yaml
    key_groups:
      - pgp:
        - *bemeurer
        - *sartre
  - path_regex: users/bemeurer/bemeurer-password.yaml
    key_groups:
      - pgp:
        - *bemeurer
        - *aurelius
        - *cantor
        - *deleuze
        - *feuerbach
        - *foucault
        - *fourier
        - *goethe
        - *hegel
        - *riemann
        - *sartre
  - path_regex: hosts/aurelius/root-password.yaml
    key_groups:
      - pgp:
        - *bemeurer
        - *aurelius
  - path_regex: hosts/cantor/root-password.yaml
    key_groups:
      - pgp:
        - *bemeurer
        - *cantor
  - path_regex: hosts/deleuze/root-password.yaml
    key_groups:
      - pgp:
        - *bemeurer
        - *deleuze
  - path_regex: hosts/feuerbach/root-password.yaml
    key_groups:
      - pgp:
        - *bemeurer
        - *feuerbach
  - path_regex: hosts/foucault/root-password.yaml
    key_groups:
      - pgp:
        - *bemeurer
        - *foucault
  - path_regex: hosts/fourier/root-password.yaml
    key_groups:
      - pgp:
        - *bemeurer
        - *fourier
  - path_regex: hosts/goethe/root-password.yaml
    key_groups:
      - pgp:
        - *bemeurer
        - *goethe
  - path_regex: hosts/hegel/root-password.yaml
    key_groups:
      - pgp:
        - *bemeurer
        - *hegel
  - path_regex: hosts/riemann/root-password.yaml
    key_groups:
      - pgp:
        - *bemeurer
        - *riemann
  - path_regex: hosts/sartre/root-password.yaml
    key_groups:
      - pgp:
        - *bemeurer
        - *sartre
