on:
  push:
    branches: [ "master" ]

name: CI

jobs:
    parsing:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Setup Nix
          uses: cachix/install-nix-action@v6
        - name: Parsing tests
          run: find . -name "*.nix" -exec nix-instantiate --parse --quiet {} >/dev/null +
    formatting:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Setup Nix
          uses: cachix/install-nix-action@v6
        - name: Formatting tests
          run: nix run nixpkgs.nixfmt -c find . -iname "*.nix" -exec nixfmt -c {} +
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Setup Nix
          uses: cachix/install-nix-action@v6
        - name: Setup channel
          run: |
            nix-channel --add https://nixos.org/channels/nixos-unstable nixpkgs
            nix-channel --update
        - name: Setup cachix
          uses: cachix/cachix-action@v3
          with:
              name: nix-config
              signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
              skipNixBuild: true
        - name: Setup home-manager
          env:
            NIX_PATH: "/home/runner/.nix-defexpr/channels:nixpkgs=/nix/var/nix/profiles/per-user/root/channels/nixos:/nix/var/nix/profiles/per-user/root/channels"
          run: |
            nix-channel --add https://github.com/rycee/home-manager/archive/master.tar.gz home-manager
            nix-channel --update
            nix-shell '<home-manager>' -A install
            echo "{ allowUnfree = true; }" > ~/.config/nixpkgs/config.nix
        - name: Setup AArch64 Build Box
          run: |
            sudo mkdir -p /root/.ssh
            echo "${{ secrets.AARCH64_BOX_KEY }}" | sudo tee /root/.ssh/aarch64.community.nixos > /dev/null
            echo "${{ secrets.KNOWN_HOSTS }}" | sudo tee -a /root/.ssh/known_hosts > /dev/null
            echo "lovesegfault@aarch64.nixos.community aarch64-linux /root/.ssh/aarch64.community.nixos 64 8 big-parallel" | sudo tee /etc/nix/machines > /dev/null
        - name: Build machines
          run: nix build -f. --keep-going foucault
        - name: Push to Cachix
          run: cachix push nix-config ./result*
