on:
  push:
    branches: [ "*" ]

name: CI

jobs:
###############################################################################
    parsing:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Nix
          uses: cachix/install-nix-action@v7
        - name: Parsing tests
          run: find . -name "*.nix" -exec nix-instantiate --parse --quiet {} >/dev/null +
    formatting:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Nix
          uses: cachix/install-nix-action@v7
        - name: Cachix
          uses: cachix/cachix-action@v4
          with:
              name: nix-config
              signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
              skipNixBuild: true
        - name: Formatting tests
          run: nix-shell --run 'find . -iname "*.nix" -not -path ./nix/sources.nix -exec nixpkgs-fmt --check {} +'
###############################################################################
    build_bohr:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Nix
          uses: cachix/install-nix-action@v7
        - name: AArch64 Build Box
          run: |
            # first create the ssh config dir for root
            sudo mkdir -p /root/.ssh

            # now add the key for the build slave
            echo "${{ secrets.AARCH64_BOX_KEY }}" |
                sudo tee /root/.ssh/aarch64.community.nixos > /dev/null
            sudo chmod 0600 /root/.ssh/aarch64.community.nixos

            # and make it a known host
            echo "${{ secrets.KNOWN_HOSTS }}" |
                sudo tee -a /root/.ssh/known_hosts > /dev/null

            # lastly register the build slave with nix
            slave_cfg=(
              lovesegfault@aarch64.nixos.community # user/addr
              aarch64-linux                        # arch
              /root/.ssh/aarch64.community.nixos   # key
              64                                   # maxJobs
              8                                    # speed factor
              big-parallel                         # features
            )
            echo "${slave_cfg[*]}" |
                sudo tee /etc/nix/machines > /dev/null
        - name: Cachix
          uses: cachix/cachix-action@v4
          with:
              attributes: bohr
              name: nix-config
              signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    build_camus:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Nix
          uses: cachix/install-nix-action@v7
        - name: AArch64 Build Box
          run: |
            # first create the ssh config dir for root
            sudo mkdir -p /root/.ssh

            # now add the key for the build slave
            echo "${{ secrets.AARCH64_BOX_KEY }}" |
                sudo tee /root/.ssh/aarch64.community.nixos > /dev/null
            sudo chmod 0600 /root/.ssh/aarch64.community.nixos

            # and make it a known host
            echo "${{ secrets.KNOWN_HOSTS }}" |
                sudo tee -a /root/.ssh/known_hosts > /dev/null

            # lastly register the build slave with nix
            slave_cfg=(
              lovesegfault@aarch64.nixos.community # user/addr
              aarch64-linux                        # arch
              /root/.ssh/aarch64.community.nixos   # key
              64                                   # maxJobs
              8                                    # speed factor
              big-parallel                         # features
            )
            echo "${slave_cfg[*]}" |
                sudo tee /etc/nix/machines > /dev/null
        - name: Cachix
          uses: cachix/cachix-action@v4
          with:
              attributes: camus
              name: nix-config
              signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
###############################################################################
    build_abel:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Nix
          uses: cachix/install-nix-action@v7
        - name: Cachix
          uses: cachix/cachix-action@v4
          with:
              attributes: abel
              name: nix-config
              signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    build_cantor:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Nix
          uses: cachix/install-nix-action@v7
        - name: Cachix
          uses: cachix/cachix-action@v4
          with:
              attributes: cantor
              name: nix-config
              signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    build_foucault:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Nix
          uses: cachix/install-nix-action@v7
        - name: Cachix
          uses: cachix/cachix-action@v4
          with:
              attributes: foucault
              name: nix-config
              signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    build_peano:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Nix
          uses: cachix/install-nix-action@v7
        - name: Cachix
          uses: cachix/cachix-action@v4
          with:
              attributes: peano
              name: nix-config
              signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    build_sartre:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Nix
          uses: cachix/install-nix-action@v7
        - name: Cachix
          uses: cachix/cachix-action@v4
          with:
              attributes: sartre
              name: nix-config
              signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
