{
  "jobs": {
    "cantor": {
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "name": "Checkout",
          "uses": "actions/checkout@v2"
        },
        {
          "name": "Nix",
          "uses": "cachix/install-nix-action@v10",
          "with": {
            "skip_adding_nixpkgs_channel": true
          }
        },
        {
          "name": "AArch64",
          "run": "# first create the ssh config dir for root\nsudo mkdir -p /root/.ssh\n\n# now add the key for the build slave\necho \"${{ secrets.AARCH64_BOX_KEY }}\" |\n    sudo tee /root/.ssh/aarch64.community.nixos > /dev/null\nsudo chmod 0600 /root/.ssh/aarch64.community.nixos\n\n# and make it a known host\necho \"${{ secrets.KNOWN_HOSTS }}\" |\n    sudo tee -a /root/.ssh/known_hosts > /dev/null\n\n# lastly register the build slave with nix\nslave_cfg=(\n  lovesegfault@aarch64.nixos.community # user/addr\n  aarch64-linux                        # arch\n  /root/.ssh/aarch64.community.nixos   # key\n  64                                   # maxJobs\n  1                                    # speed factor\n  big-parallel                         # features\n)\necho \"${slave_cfg[*]}\" |\n    sudo tee /etc/nix/machines > /dev/null\n"
        },
        {
          "name": "Cachix",
          "uses": "cachix/cachix-action@v6",
          "with": {
            "name": "nix-config",
            "signingKey": "'${{ secrets.CACHIX_SIGNING_KEY }}'"
          }
        },
        {
          "name": "Build",
          "run": "nix-build -A cantor"
        }
      ]
    },
    "checkCI": {
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "name": "Checkout",
          "uses": "actions/checkout@v2"
        },
        {
          "name": "Nix",
          "uses": "cachix/install-nix-action@v10",
          "with": {
            "skip_adding_nixpkgs_channel": true
          }
        },
        {
          "name": "AArch64",
          "run": "# first create the ssh config dir for root\nsudo mkdir -p /root/.ssh\n\n# now add the key for the build slave\necho \"${{ secrets.AARCH64_BOX_KEY }}\" |\n    sudo tee /root/.ssh/aarch64.community.nixos > /dev/null\nsudo chmod 0600 /root/.ssh/aarch64.community.nixos\n\n# and make it a known host\necho \"${{ secrets.KNOWN_HOSTS }}\" |\n    sudo tee -a /root/.ssh/known_hosts > /dev/null\n\n# lastly register the build slave with nix\nslave_cfg=(\n  lovesegfault@aarch64.nixos.community # user/addr\n  aarch64-linux                        # arch\n  /root/.ssh/aarch64.community.nixos   # key\n  64                                   # maxJobs\n  1                                    # speed factor\n  big-parallel                         # features\n)\necho \"${slave_cfg[*]}\" |\n    sudo tee /etc/nix/machines > /dev/null\n"
        },
        {
          "name": "Cachix",
          "uses": "cachix/cachix-action@v6",
          "with": {
            "name": "nix-config",
            "signingKey": "'${{ secrets.CACHIX_SIGNING_KEY }}'"
          }
        },
        {
          "name": "Check CI",
          "run": "cp ./.github/workflows/ci.yml /tmp/ci.yml.old\nnix-shell --run 'genci'\ndiff ./.github/workflows/ci.yml /tmp/ci.yml.old || exit 1\n"
        }
      ]
    },
    "formatting": {
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "name": "Checkout",
          "uses": "actions/checkout@v2"
        },
        {
          "name": "Nix",
          "uses": "cachix/install-nix-action@v10",
          "with": {
            "skip_adding_nixpkgs_channel": true
          }
        },
        {
          "name": "AArch64",
          "run": "# first create the ssh config dir for root\nsudo mkdir -p /root/.ssh\n\n# now add the key for the build slave\necho \"${{ secrets.AARCH64_BOX_KEY }}\" |\n    sudo tee /root/.ssh/aarch64.community.nixos > /dev/null\nsudo chmod 0600 /root/.ssh/aarch64.community.nixos\n\n# and make it a known host\necho \"${{ secrets.KNOWN_HOSTS }}\" |\n    sudo tee -a /root/.ssh/known_hosts > /dev/null\n\n# lastly register the build slave with nix\nslave_cfg=(\n  lovesegfault@aarch64.nixos.community # user/addr\n  aarch64-linux                        # arch\n  /root/.ssh/aarch64.community.nixos   # key\n  64                                   # maxJobs\n  1                                    # speed factor\n  big-parallel                         # features\n)\necho \"${slave_cfg[*]}\" |\n    sudo tee /etc/nix/machines > /dev/null\n"
        },
        {
          "name": "Cachix",
          "uses": "cachix/cachix-action@v6",
          "with": {
            "name": "nix-config",
            "signingKey": "'${{ secrets.CACHIX_SIGNING_KEY }}'"
          }
        },
        {
          "name": "Formatting",
          "run": "nix-shell --run 'nixpkgs-fmt --check .'"
        }
      ]
    },
    "fourier": {
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "name": "Checkout",
          "uses": "actions/checkout@v2"
        },
        {
          "name": "Nix",
          "uses": "cachix/install-nix-action@v10",
          "with": {
            "skip_adding_nixpkgs_channel": true
          }
        },
        {
          "name": "AArch64",
          "run": "# first create the ssh config dir for root\nsudo mkdir -p /root/.ssh\n\n# now add the key for the build slave\necho \"${{ secrets.AARCH64_BOX_KEY }}\" |\n    sudo tee /root/.ssh/aarch64.community.nixos > /dev/null\nsudo chmod 0600 /root/.ssh/aarch64.community.nixos\n\n# and make it a known host\necho \"${{ secrets.KNOWN_HOSTS }}\" |\n    sudo tee -a /root/.ssh/known_hosts > /dev/null\n\n# lastly register the build slave with nix\nslave_cfg=(\n  lovesegfault@aarch64.nixos.community # user/addr\n  aarch64-linux                        # arch\n  /root/.ssh/aarch64.community.nixos   # key\n  64                                   # maxJobs\n  1                                    # speed factor\n  big-parallel                         # features\n)\necho \"${slave_cfg[*]}\" |\n    sudo tee /etc/nix/machines > /dev/null\n"
        },
        {
          "name": "Cachix",
          "uses": "cachix/cachix-action@v6",
          "with": {
            "name": "nix-config",
            "signingKey": "'${{ secrets.CACHIX_SIGNING_KEY }}'"
          }
        },
        {
          "name": "Build",
          "run": "nix-build -A fourier"
        }
      ]
    },
    "goethe": {
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "name": "Checkout",
          "uses": "actions/checkout@v2"
        },
        {
          "name": "Nix",
          "uses": "cachix/install-nix-action@v10",
          "with": {
            "skip_adding_nixpkgs_channel": true
          }
        },
        {
          "name": "AArch64",
          "run": "# first create the ssh config dir for root\nsudo mkdir -p /root/.ssh\n\n# now add the key for the build slave\necho \"${{ secrets.AARCH64_BOX_KEY }}\" |\n    sudo tee /root/.ssh/aarch64.community.nixos > /dev/null\nsudo chmod 0600 /root/.ssh/aarch64.community.nixos\n\n# and make it a known host\necho \"${{ secrets.KNOWN_HOSTS }}\" |\n    sudo tee -a /root/.ssh/known_hosts > /dev/null\n\n# lastly register the build slave with nix\nslave_cfg=(\n  lovesegfault@aarch64.nixos.community # user/addr\n  aarch64-linux                        # arch\n  /root/.ssh/aarch64.community.nixos   # key\n  64                                   # maxJobs\n  1                                    # speed factor\n  big-parallel                         # features\n)\necho \"${slave_cfg[*]}\" |\n    sudo tee /etc/nix/machines > /dev/null\n"
        },
        {
          "name": "Cachix",
          "uses": "cachix/cachix-action@v6",
          "with": {
            "name": "nix-config",
            "signingKey": "'${{ secrets.CACHIX_SIGNING_KEY }}'"
          }
        },
        {
          "name": "Build",
          "run": "nix-build -A goethe"
        }
      ]
    },
    "hegel": {
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "name": "Checkout",
          "uses": "actions/checkout@v2"
        },
        {
          "name": "Nix",
          "uses": "cachix/install-nix-action@v10",
          "with": {
            "skip_adding_nixpkgs_channel": true
          }
        },
        {
          "name": "AArch64",
          "run": "# first create the ssh config dir for root\nsudo mkdir -p /root/.ssh\n\n# now add the key for the build slave\necho \"${{ secrets.AARCH64_BOX_KEY }}\" |\n    sudo tee /root/.ssh/aarch64.community.nixos > /dev/null\nsudo chmod 0600 /root/.ssh/aarch64.community.nixos\n\n# and make it a known host\necho \"${{ secrets.KNOWN_HOSTS }}\" |\n    sudo tee -a /root/.ssh/known_hosts > /dev/null\n\n# lastly register the build slave with nix\nslave_cfg=(\n  lovesegfault@aarch64.nixos.community # user/addr\n  aarch64-linux                        # arch\n  /root/.ssh/aarch64.community.nixos   # key\n  64                                   # maxJobs\n  1                                    # speed factor\n  big-parallel                         # features\n)\necho \"${slave_cfg[*]}\" |\n    sudo tee /etc/nix/machines > /dev/null\n"
        },
        {
          "name": "Cachix",
          "uses": "cachix/cachix-action@v6",
          "with": {
            "name": "nix-config",
            "signingKey": "'${{ secrets.CACHIX_SIGNING_KEY }}'"
          }
        },
        {
          "name": "Build",
          "run": "nix-build -A hegel"
        }
      ]
    },
    "parsing": {
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "name": "Checkout",
          "uses": "actions/checkout@v2"
        },
        {
          "name": "Nix",
          "uses": "cachix/install-nix-action@v10",
          "with": {
            "skip_adding_nixpkgs_channel": true
          }
        },
        {
          "name": "AArch64",
          "run": "# first create the ssh config dir for root\nsudo mkdir -p /root/.ssh\n\n# now add the key for the build slave\necho \"${{ secrets.AARCH64_BOX_KEY }}\" |\n    sudo tee /root/.ssh/aarch64.community.nixos > /dev/null\nsudo chmod 0600 /root/.ssh/aarch64.community.nixos\n\n# and make it a known host\necho \"${{ secrets.KNOWN_HOSTS }}\" |\n    sudo tee -a /root/.ssh/known_hosts > /dev/null\n\n# lastly register the build slave with nix\nslave_cfg=(\n  lovesegfault@aarch64.nixos.community # user/addr\n  aarch64-linux                        # arch\n  /root/.ssh/aarch64.community.nixos   # key\n  64                                   # maxJobs\n  1                                    # speed factor\n  big-parallel                         # features\n)\necho \"${slave_cfg[*]}\" |\n    sudo tee /etc/nix/machines > /dev/null\n"
        },
        {
          "name": "Cachix",
          "uses": "cachix/cachix-action@v6",
          "with": {
            "name": "nix-config",
            "signingKey": "'${{ secrets.CACHIX_SIGNING_KEY }}'"
          }
        },
        {
          "name": "Parsing",
          "run": "find . -name \"*.nix\" -exec nix-instantiate --parse --quiet {} >/dev/null +"
        }
      ]
    },
    "peano": {
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "name": "Checkout",
          "uses": "actions/checkout@v2"
        },
        {
          "name": "Nix",
          "uses": "cachix/install-nix-action@v10",
          "with": {
            "skip_adding_nixpkgs_channel": true
          }
        },
        {
          "name": "AArch64",
          "run": "# first create the ssh config dir for root\nsudo mkdir -p /root/.ssh\n\n# now add the key for the build slave\necho \"${{ secrets.AARCH64_BOX_KEY }}\" |\n    sudo tee /root/.ssh/aarch64.community.nixos > /dev/null\nsudo chmod 0600 /root/.ssh/aarch64.community.nixos\n\n# and make it a known host\necho \"${{ secrets.KNOWN_HOSTS }}\" |\n    sudo tee -a /root/.ssh/known_hosts > /dev/null\n\n# lastly register the build slave with nix\nslave_cfg=(\n  lovesegfault@aarch64.nixos.community # user/addr\n  aarch64-linux                        # arch\n  /root/.ssh/aarch64.community.nixos   # key\n  64                                   # maxJobs\n  1                                    # speed factor\n  big-parallel                         # features\n)\necho \"${slave_cfg[*]}\" |\n    sudo tee /etc/nix/machines > /dev/null\n"
        },
        {
          "name": "Cachix",
          "uses": "cachix/cachix-action@v6",
          "with": {
            "name": "nix-config",
            "signingKey": "'${{ secrets.CACHIX_SIGNING_KEY }}'"
          }
        },
        {
          "name": "Build",
          "run": "nix-build -A peano"
        }
      ]
    },
    "sartre": {
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "name": "Checkout",
          "uses": "actions/checkout@v2"
        },
        {
          "name": "Nix",
          "uses": "cachix/install-nix-action@v10",
          "with": {
            "skip_adding_nixpkgs_channel": true
          }
        },
        {
          "name": "AArch64",
          "run": "# first create the ssh config dir for root\nsudo mkdir -p /root/.ssh\n\n# now add the key for the build slave\necho \"${{ secrets.AARCH64_BOX_KEY }}\" |\n    sudo tee /root/.ssh/aarch64.community.nixos > /dev/null\nsudo chmod 0600 /root/.ssh/aarch64.community.nixos\n\n# and make it a known host\necho \"${{ secrets.KNOWN_HOSTS }}\" |\n    sudo tee -a /root/.ssh/known_hosts > /dev/null\n\n# lastly register the build slave with nix\nslave_cfg=(\n  lovesegfault@aarch64.nixos.community # user/addr\n  aarch64-linux                        # arch\n  /root/.ssh/aarch64.community.nixos   # key\n  64                                   # maxJobs\n  1                                    # speed factor\n  big-parallel                         # features\n)\necho \"${slave_cfg[*]}\" |\n    sudo tee /etc/nix/machines > /dev/null\n"
        },
        {
          "name": "Cachix",
          "uses": "cachix/cachix-action@v6",
          "with": {
            "name": "nix-config",
            "signingKey": "'${{ secrets.CACHIX_SIGNING_KEY }}'"
          }
        },
        {
          "name": "Build",
          "run": "nix-build -A sartre"
        }
      ]
    }
  },
  "name": "CI",
  "on": [
    "pull_request",
    "push"
  ]
}
