name: niv update
on:
  schedule:
    # run this every day at 4:00am
    - cron:  '0 0 * * mon,wed,fri'
jobs:
  niv-updater:
    name: 'Create PRs for niv-managed dependencies'
    runs-on: ubuntu-latest
    steps:
      - name: niv-updater-action
        uses: knl/niv-updater-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch_prefix: 'update/'
          show_merges: false
